project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "snf-payroll-ranker/index.qmd"
    - "notebooks/pr_graph/eda_04_intraday_news_execution.ipynb"
    - "notebooks/target_engineering/eda_01_target_engineering.ipynb"
    - "notebooks/kirsh_psi/portfolio_strategies_returns_analysis.ipynb"
    - "snf-payroll-ranker/snf_payroll_ranker_report.ipynb"

website:
  title: "Nathan's Research"
  navbar:
    right:
      - text: "Trading Research"
        href: trading-research.qmd
      - text: "SNF Payroll Ranker"
        href: snf-payroll-ranker/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/nrenzoni
      - icon: linkedin
        href: https://www.linkedin.com/in/nathan-renzoni
        
format:
  html:
    theme: cosmo
    css: styles.css
    
toc: true
toc-location: "left"
toc-title: "Contents"

execute:
  freeze: true
